// sw.js — offline support: precaches the whole show on install, then serves it cache-first.
// The asset list and VERSION below are generated by `python tools/precache.py` — rerun it after changing files.

/* precache:start */
const VERSION = '399dcc5117e7';
const BYTES = 3080355;
const ASSETS = [
  "./",
  "index.html",
  "manifest.webmanifest",
  "css/style.css",
  "js/audio.js",
  "js/confetti.js",
  "js/install.js",
  "js/main.js",
  "js/prize-wreath.js",
  "js/prize-zonk.js",
  "js/prizes.js",
  "js/stage.js",
  "assets/favicon.svg",
  "assets/icon-180.png",
  "assets/icon-192.png",
  "assets/icon-512.png",
  "assets/icon-maskable-512.png",
  "vendor/fonts/bungee-400-latin-ext.woff2",
  "vendor/fonts/bungee-400-latin.woff2",
  "vendor/fonts/fonts.css",
  "vendor/fonts/manrope-400-latin-ext.woff2",
  "vendor/fonts/manrope-400-latin.woff2",
  "vendor/fonts/manrope-600-latin-ext.woff2",
  "vendor/fonts/manrope-600-latin.woff2",
  "vendor/fonts/manrope-800-latin-ext.woff2",
  "vendor/fonts/manrope-800-latin.woff2",
  "vendor/fonts/noto-color-emoji-tear.woff2",
  "vendor/fonts/titan-one-400-latin-ext.woff2",
  "vendor/fonts/titan-one-400-latin.woff2",
  "vendor/gsap/CSSPlugin.js",
  "vendor/gsap/CustomEase.js",
  "vendor/gsap/gsap-core.js",
  "vendor/gsap/index.js",
  "vendor/gsap/utils/paths.js",
  "vendor/three/build/three.core.js",
  "vendor/three/build/three.module.js",
  "vendor/three/examples/jsm/capabilities/WebGL.js",
  "vendor/three/examples/jsm/geometries/RoundedBoxGeometry.js",
  "vendor/three/examples/jsm/postprocessing/EffectComposer.js",
  "vendor/three/examples/jsm/postprocessing/FilmPass.js",
  "vendor/three/examples/jsm/postprocessing/MaskPass.js",
  "vendor/three/examples/jsm/postprocessing/OutputPass.js",
  "vendor/three/examples/jsm/postprocessing/Pass.js",
  "vendor/three/examples/jsm/postprocessing/RenderPass.js",
  "vendor/three/examples/jsm/postprocessing/ShaderPass.js",
  "vendor/three/examples/jsm/postprocessing/UnrealBloomPass.js",
  "vendor/three/examples/jsm/shaders/CopyShader.js",
  "vendor/three/examples/jsm/shaders/FilmShader.js",
  "vendor/three/examples/jsm/shaders/LuminosityHighPassShader.js",
  "vendor/three/examples/jsm/shaders/OutputShader.js",
  "vendor/three/examples/jsm/shaders/VignetteShader.js",
  "vendor/three/examples/jsm/utils/BufferGeometryUtils.js"
];
/* precache:end */

const CACHE = `gag-${VERSION}`;

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // bypass the HTTP cache so a fresh deploy never mixes old and new files
    await cache.addAll(ASSETS.map((url) => new Request(url, { cache: 'reload' })));
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((k) => k.startsWith('gag-') && k !== CACHE).map((k) => caches.delete(k)));
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET' || new URL(request.url).origin !== self.location.origin) return;
  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const hit = await cache.match(request, { ignoreSearch: true });
    if (hit) return hit;
    try {
      return await fetch(request);
    } catch (err) {
      if (request.mode === 'navigate') return (await cache.match('./')) || Response.error();
      throw err;
    }
  })());
});

self.addEventListener('message', (event) => {
  if (event.data?.type !== 'status') return;
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    const cached = (await cache.keys()).length;
    event.source?.postMessage({ type: 'status', cached, total: ASSETS.length, bytes: BYTES, version: VERSION });
  })());
});
